#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

#Run linter
cd ./client; # Mover esto a la build del client una vez API esté listo
#npm run lint;

#Go to Client folder and check the build
#npm run build;

# Return to root folder
# cd ..;

# Go to API folder and and typecheck
# cd ./api;
#npm run typecheck;

